LoanApplication/Controllers/LoanController.cs
using LoanApplication.Data;
using LoanApplication.Models;
using Microsoft.AspNetCore.Mvc;

namespace LoanApplication.Controllers
{
    public class LoanController : Controller
    {
        private readonly AppDataBaseContext _dataBase;

        public LoanController (AppDataBaseContext _dataBase)
        {
            this._dataBase = _dataBase;
        }



        public IActionResult LoanView()
        {
          var loanObjList = _dataBase.Loans.ToList();

            
            return View(loanObjList);
        }

        //To return the view 
        public IActionResult GetLoaner()
        {

            return View();   

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult GetLoaner(LoanModel loanObj)
        {



        


                loanObj = UtilityMethod(loanObj);

            _dataBase.Loans.Add(loanObj);
            _dataBase.SaveChanges();

            return RedirectToAction("LoanView");
            

            return View(loanObj);
            
        }



        public IActionResult Update(int? id)
        {
            if(id == null && id==0)
            {
                return NotFound();
            }
            var loanObj = _dataBase.Loans.Find(id);
            
            
            
            return View(loanObj);

        }

        [HttpPost]
        public IActionResult Update(LoanModel loanObj)
        {

            loanObj = UtilityMethod(loanObj);
          _dataBase.Loans.Update(loanObj);
            _dataBase.SaveChanges();
            return RedirectToAction("LoanView");

            return View(loanObj);
        }


        //Get method for delete
        public IActionResult Delete(int? id) 
        {
            if (id == null && id == 0)
            {
                return NotFound();
            }
            var loanObj = _dataBase.Loans.Find(id);
            return View(loanObj);
        }

        [HttpPost]
        public IActionResult Delete(LoanModel loanObj)
        {
            loanObj = UtilityMethod(loanObj);
            _dataBase.Loans.Remove(loanObj);
            _dataBase.SaveChanges();
            return RedirectToAction("LoanView");

            return View(loanObj);
        }

        public IActionResult Details(int? id)
        {
            if (id == null && id == 0)
            {
                return NotFound();
            }
            var loanObj = _dataBase.Loans.Find(id);
            return View(loanObj);
        }


       


       // Utility method
        public LoanModel UtilityMethod(LoanModel loanObj)
        {
            float maximumInst = 0;
            float loanGranted = 0;
            float deposite = 0;
            float monthlyInstall = 0;
            
            

            //100% loan
            if (loanObj.CreditScore >= 800)
            {
                maximumInst = MaximumInstalCal(loanObj.GrossSalary);
                loanObj.LoanStatus = "Granted";
                loanGranted = loanGrantedCal(100);
                deposite = DepositeReqCal(loanObj.PriceOfProperty,loanGranted);
                monthlyInstall = MonthlyInstalCal(loanObj.PriceOfProperty, deposite);
            }
            //97.5 loan
            else if (loanObj.CreditScore >= 750 && loanObj.CreditScore <= 799)
            {
                
                maximumInst = MaximumInstalCal(loanObj.GrossSalary);
                loanObj.LoanStatus = "Granted";
                loanGranted = loanGrantedCal(97.5);
                deposite = DepositeReqCal(loanObj.PriceOfProperty, loanGranted);
                monthlyInstall = MonthlyInstalCal(loanObj.PriceOfProperty, deposite);
            }
            //95% loan
            else if (loanObj.CreditScore >= 700 && loanObj.CreditScore <= 749)
            {

                maximumInst = MaximumInstalCal(loanObj.GrossSalary);
                loanObj.LoanStatus = "Granted";
                loanGranted = loanGrantedCal(95);
                deposite = DepositeReqCal(loanObj.PriceOfProperty, loanGranted);
                monthlyInstall = MonthlyInstalCal(loanObj.PriceOfProperty, deposite);
            }

            //90% loan
            else if (loanObj.CreditScore >= 650 && loanObj.CreditScore <= 699)
            {
                maximumInst = MaximumInstalCal(loanObj.GrossSalary);
                loanObj.LoanStatus = "Granted";
                loanGranted =loanGrantedCal(90);
                deposite = DepositeReqCal(loanObj.PriceOfProperty, loanGranted);
                monthlyInstall = MonthlyInstalCal(loanObj.PriceOfProperty, deposite);
            }
            //85% loan
            else if (loanObj.CreditScore >= 600 && loanObj.CreditScore <= 649)
            {
                maximumInst = MaximumInstalCal(loanObj.GrossSalary);
                loanObj.LoanStatus = "Granted";
                loanGranted = loanGrantedCal(85);
                deposite = DepositeReqCal(loanObj.PriceOfProperty,  loanGranted);
                monthlyInstall = MonthlyInstalCal(loanObj.PriceOfProperty, deposite);
            }
            //80% loan
            else if (loanObj.CreditScore >= 550 && loanObj.CreditScore <= 599)
            {
                maximumInst = MaximumInstalCal(loanObj.GrossSalary);
                loanObj.LoanStatus = "Granted";
                loanGranted = loanGrantedCal(80);
                deposite = DepositeReqCal(loanObj.PriceOfProperty, loanGranted);
                monthlyInstall = MonthlyInstalCal(loanObj.PriceOfProperty, deposite);
            }
            //No loan
            else if (loanObj.CreditScore <= 549)
            {
                maximumInst = 0;
                loanObj.LoanStatus = "Rejected";
                loanGranted = 0;
                deposite = 0;
                monthlyInstall = 0;
            }

            loanObj = new LoanModel
            {
                ID = loanObj.ID,
                Name = loanObj.Name,
                Surname = loanObj.Surname,
                GrossSalary = loanObj.GrossSalary,
                CreditScore = loanObj.CreditScore,
                PriceOfProperty = loanObj.PriceOfProperty,
                LoanStatus = loanObj.LoanStatus,
                MaximumInstalment = maximumInst,
                LoanGranted = loanGranted,
                DepositeRequired = deposite,
                MonthlyInstalment = monthlyInstall


            };

            return loanObj;

        }

        public float MaximumInstalCal(float grossSalary)
        {
            float maxInstal = grossSalary * 30 / 100;

            return maxInstal;
        }

        public float loanGrantedCal(double loangrant)
        {
            float loanGranted = (float)(loangrant);
            return loanGranted;
        }
    

        public float DepositeReqCal(float priceOfPropery,float loanGranted)
        {
            float deposite = priceOfPropery - (priceOfPropery * loanGranted/100);

            return deposite;
        }
        public float MonthlyInstalCal(float priceOfproperty, float deposite)
        {
            float monthlyInstall = (float)((priceOfproperty - deposite) * ((double)0.00785));

            return monthlyInstall;
        }
    }
}

LoanApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>LoanApplication</title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" integrity="..." />
   
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LoanApplication.styles.css" asp-append-version="true" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg glassBackground">
            <div class="container-fluid text-black " >
                <a class="navbar-brand  text-black-50" asp-area="" asp-controller="Home" asp-action="Index">LoanApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" 
                aria-controls="navbarColor02"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse collapse " id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        @*<li class="nav-item">
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="navbar-brand  text-black-50" asp-area="" asp-controller="Loan" asp-action="LoanView">Home Loans</a>
                        </li>
                     
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container text-white " >
       
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <br/>
    <br/>
    <br/>
    <footer class="border-top footer text-muted text-dark" style="margin-top:200px;">
        <div class="container text-dark">
            &copy; 2024 - LoanApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>